In [6]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(32),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch()


EPOCH: 0
LOSS: tf.Tensor(94.02095031738281, shape=(), dtype=float64)
EPOCH: 1
LOSS: tf.Tensor(93.45323181152344, shape=(), dtype=float64)
EPOCH: 2
LOSS: tf.Tensor(92.86457824707031, shape=(), dtype=float64)
EPOCH: 3
LOSS: tf.Tensor(92.26669311523438, shape=(), dtype=float64)
EPOCH: 4
LOSS: tf.Tensor(91.65855407714844, shape=(), dtype=float64)
EPOCH: 5
LOSS: tf.Tensor(91.04164123535156, shape=(), dtype=float64)
EPOCH: 6
LOSS: tf.Tensor(90.41934204101562, shape=(), dtype=float64)
EPOCH: 7
LOSS: tf.Tensor(89.78291320800781, shape=(), dtype=float64)
EPOCH: 8
LOSS: tf.Tensor(89.12913513183594, shape=(), dtype=float64)
EPOCH: 9
LOSS: tf.Tensor(88.45684814453125, shape=(), dtype=float64)
EPOCH: 10
LOSS: tf.Tensor(87.7689208984375, shape=(), dtype=float64)
EPOCH: 11
LOSS: tf.Tensor(87.0560302734375, shape=(), dtype=float64)
EPOCH: 12
LOSS: tf.Tensor(86.31688690185547, shape=(), dtype=float64)
EPOCH: 13
LOSS: tf.Tensor(85.55348205566406, shape=(), dtype=float64)
EPOCH: 14
LOSS: tf.Tensor(84.768

In [7]:
testModel(test_set[1000:1010])


Prediction: tf.Tensor([[8.19474234]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[6.89234235]], shape=(1, 1), dtype=float64) True Value: [2.]
Prediction: tf.Tensor([[8.27988223]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[9.37949634]], shape=(1, 1), dtype=float64) True Value: [5.21]
Prediction: tf.Tensor([[5.71535886]], shape=(1, 1), dtype=float64) True Value: [6.65]
Prediction: tf.Tensor([[9.36149519]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[5.84217027]], shape=(1, 1), dtype=float64) True Value: [10.]
Prediction: tf.Tensor([[6.86213577]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[7.32432644]], shape=(1, 1), dtype=float64) True Value: [6.68]
Prediction: tf.Tensor([[8.58061516]], shape=(1, 1), dtype=float64) True Value: [7.65]


In [10]:
testModel(test_set[500:510])


Prediction: tf.Tensor([[8.15521395]], shape=(1, 1), dtype=float64) True Value: [0.15]
Prediction: tf.Tensor([[7.13400382]], shape=(1, 1), dtype=float64) True Value: [2.87]
Prediction: tf.Tensor([[4.946878]], shape=(1, 1), dtype=float64) True Value: [9.73]
Prediction: tf.Tensor([[8.84512077]], shape=(1, 1), dtype=float64) True Value: [7.45]
Prediction: tf.Tensor([[10.68216866]], shape=(1, 1), dtype=float64) True Value: [8.75]
Prediction: tf.Tensor([[10.09979306]], shape=(1, 1), dtype=float64) True Value: [8.88]
Prediction: tf.Tensor([[8.56463765]], shape=(1, 1), dtype=float64) True Value: [6.15]
Prediction: tf.Tensor([[12.10893007]], shape=(1, 1), dtype=float64) True Value: [11.67]
Prediction: tf.Tensor([[5.39479518]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[9.41228265]], shape=(1, 1), dtype=float64) True Value: [8.]


In [11]:
testModel(test_set[3000:3010])


Prediction: tf.Tensor([[7.65856379]], shape=(1, 1), dtype=float64) True Value: [3.]
Prediction: tf.Tensor([[8.41690892]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[8.52455593]], shape=(1, 1), dtype=float64) True Value: [7.25]
Prediction: tf.Tensor([[9.05401944]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[6.448586]], shape=(1, 1), dtype=float64) True Value: [6.]
Prediction: tf.Tensor([[2.06467699]], shape=(1, 1), dtype=float64) True Value: [3.07]
Prediction: tf.Tensor([[3.87427398]], shape=(1, 1), dtype=float64) True Value: [4.3]
Prediction: tf.Tensor([[8.72105339]], shape=(1, 1), dtype=float64) True Value: [8.3]
Prediction: tf.Tensor([[9.36149519]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[7.15815882]], shape=(1, 1), dtype=float64) True Value: [15.]
