In [12]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim = 14),
    tf.keras.layers.Dense(32),
    tf.keras.layers.Dense(1)
])


In [13]:
for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)
    

EPOCH: 0
LOSS: tf.Tensor(110.7230224609375, shape=(), dtype=float64)
EPOCH: 1
LOSS: tf.Tensor(108.46369934082031, shape=(), dtype=float64)
EPOCH: 2
LOSS: tf.Tensor(106.0922622680664, shape=(), dtype=float64)
EPOCH: 3
LOSS: tf.Tensor(103.74349212646484, shape=(), dtype=float64)
EPOCH: 4
LOSS: tf.Tensor(101.42878723144531, shape=(), dtype=float64)
EPOCH: 5
LOSS: tf.Tensor(99.167724609375, shape=(), dtype=float64)
EPOCH: 6
LOSS: tf.Tensor(96.97526550292969, shape=(), dtype=float64)
EPOCH: 7
LOSS: tf.Tensor(94.86026763916016, shape=(), dtype=float64)
EPOCH: 8
LOSS: tf.Tensor(92.82000732421875, shape=(), dtype=float64)
EPOCH: 9
LOSS: tf.Tensor(90.8546371459961, shape=(), dtype=float64)
EPOCH: 10
LOSS: tf.Tensor(88.97799682617188, shape=(), dtype=float64)
EPOCH: 11
LOSS: tf.Tensor(87.211669921875, shape=(), dtype=float64)
EPOCH: 12
LOSS: tf.Tensor(85.54884338378906, shape=(), dtype=float64)
EPOCH: 13
LOSS: tf.Tensor(83.9960708618164, shape=(), dtype=float64)
EPOCH: 14
LOSS: tf.Tensor(82.5510

In [15]:
testModel(test_set[1000:1010],model)


Prediction: tf.Tensor([[7.14137687]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[6.51022308]], shape=(1, 1), dtype=float64) True Value: [2.]
Prediction: tf.Tensor([[7.21089864]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[7.71819329]], shape=(1, 1), dtype=float64) True Value: [5.21]
Prediction: tf.Tensor([[5.34265159]], shape=(1, 1), dtype=float64) True Value: [6.65]
Prediction: tf.Tensor([[9.09027081]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[6.09035252]], shape=(1, 1), dtype=float64) True Value: [10.]
Prediction: tf.Tensor([[6.14444056]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[6.21050507]], shape=(1, 1), dtype=float64) True Value: [6.68]
Prediction: tf.Tensor([[7.57633998]], shape=(1, 1), dtype=float64) True Value: [7.65]


In [17]:
testModel(test_set[500:510],model)


Prediction: tf.Tensor([[7.47723398]], shape=(1, 1), dtype=float64) True Value: [0.15]
Prediction: tf.Tensor([[5.8468601]], shape=(1, 1), dtype=float64) True Value: [2.87]
Prediction: tf.Tensor([[4.52511215]], shape=(1, 1), dtype=float64) True Value: [9.73]
Prediction: tf.Tensor([[8.78059304]], shape=(1, 1), dtype=float64) True Value: [7.45]
Prediction: tf.Tensor([[9.13395604]], shape=(1, 1), dtype=float64) True Value: [8.75]
Prediction: tf.Tensor([[9.94048731]], shape=(1, 1), dtype=float64) True Value: [8.88]
Prediction: tf.Tensor([[7.52172093]], shape=(1, 1), dtype=float64) True Value: [6.15]
Prediction: tf.Tensor([[12.29408034]], shape=(1, 1), dtype=float64) True Value: [11.67]
Prediction: tf.Tensor([[5.58477364]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[9.25301289]], shape=(1, 1), dtype=float64) True Value: [8.]


In [19]:
testModel(test_set[3000:3010],model)

Prediction: tf.Tensor([[9.11983391]], shape=(1, 1), dtype=float64) True Value: [3.]
Prediction: tf.Tensor([[7.7118701]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[8.10223238]], shape=(1, 1), dtype=float64) True Value: [7.25]
Prediction: tf.Tensor([[7.69125603]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[5.91977241]], shape=(1, 1), dtype=float64) True Value: [6.]
Prediction: tf.Tensor([[2.33768485]], shape=(1, 1), dtype=float64) True Value: [3.07]
Prediction: tf.Tensor([[4.51536765]], shape=(1, 1), dtype=float64) True Value: [4.3]
Prediction: tf.Tensor([[7.27011081]], shape=(1, 1), dtype=float64) True Value: [8.3]
Prediction: tf.Tensor([[9.09027081]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[5.95611193]], shape=(1, 1), dtype=float64) True Value: [15.]


In [21]:
model = 0
#same Deep NN, adding activation functions
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim = 14, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)
    

EPOCH: 0
LOSS: tf.Tensor(102.199462890625, shape=(), dtype=float64)
EPOCH: 1
LOSS: tf.Tensor(96.69383239746094, shape=(), dtype=float64)
EPOCH: 2
LOSS: tf.Tensor(94.19489288330078, shape=(), dtype=float64)
EPOCH: 3
LOSS: tf.Tensor(92.23666381835938, shape=(), dtype=float64)
EPOCH: 4
LOSS: tf.Tensor(90.56623840332031, shape=(), dtype=float64)
EPOCH: 5
LOSS: tf.Tensor(89.06338500976562, shape=(), dtype=float64)
EPOCH: 6
LOSS: tf.Tensor(87.68280029296875, shape=(), dtype=float64)
EPOCH: 7
LOSS: tf.Tensor(86.39242553710938, shape=(), dtype=float64)
EPOCH: 8
LOSS: tf.Tensor(85.16683197021484, shape=(), dtype=float64)
EPOCH: 9
LOSS: tf.Tensor(84.00621032714844, shape=(), dtype=float64)
EPOCH: 10
LOSS: tf.Tensor(82.9095458984375, shape=(), dtype=float64)
EPOCH: 11
LOSS: tf.Tensor(81.86112213134766, shape=(), dtype=float64)
EPOCH: 12
LOSS: tf.Tensor(80.861328125, shape=(), dtype=float64)
EPOCH: 13
LOSS: tf.Tensor(79.90414428710938, shape=(), dtype=float64)
EPOCH: 14
LOSS: tf.Tensor(78.98590087

In [22]:
testModel(test_set[1000:1010],model)

Prediction: tf.Tensor([[7.73840855]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[7.15394564]], shape=(1, 1), dtype=float64) True Value: [2.]
Prediction: tf.Tensor([[7.87881379]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[7.960564]], shape=(1, 1), dtype=float64) True Value: [5.21]
Prediction: tf.Tensor([[6.6380053]], shape=(1, 1), dtype=float64) True Value: [6.65]
Prediction: tf.Tensor([[9.5629988]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[5.12022072]], shape=(1, 1), dtype=float64) True Value: [10.]
Prediction: tf.Tensor([[6.70079883]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[6.97481228]], shape=(1, 1), dtype=float64) True Value: [6.68]
Prediction: tf.Tensor([[8.83870678]], shape=(1, 1), dtype=float64) True Value: [7.65]


In [23]:
testModel(test_set[500:510],model)

Prediction: tf.Tensor([[8.29220782]], shape=(1, 1), dtype=float64) True Value: [0.15]
Prediction: tf.Tensor([[8.76892521]], shape=(1, 1), dtype=float64) True Value: [2.87]
Prediction: tf.Tensor([[3.75194107]], shape=(1, 1), dtype=float64) True Value: [9.73]
Prediction: tf.Tensor([[8.98263225]], shape=(1, 1), dtype=float64) True Value: [7.45]
Prediction: tf.Tensor([[10.77867131]], shape=(1, 1), dtype=float64) True Value: [8.75]
Prediction: tf.Tensor([[10.4591999]], shape=(1, 1), dtype=float64) True Value: [8.88]
Prediction: tf.Tensor([[8.62672372]], shape=(1, 1), dtype=float64) True Value: [6.15]
Prediction: tf.Tensor([[13.51761794]], shape=(1, 1), dtype=float64) True Value: [11.67]
Prediction: tf.Tensor([[5.59521843]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[10.1632465]], shape=(1, 1), dtype=float64) True Value: [8.]


In [1]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, input_dim = 14, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(99.3619384765625, shape=(), dtype=float64)
EPOCH: 1
LOSS: tf.Tensor(97.6746826171875, shape=(), dtype=float64)
EPOCH: 2
LOSS: tf.Tensor(96.00508880615234, shape=(), dtype=float64)
EPOCH: 3
LOSS: tf.Tensor(94.35475158691406, shape=(), dtype=float64)
EPOCH: 4
LOSS: tf.Tensor(92.72547149658203, shape=(), dtype=float64)
EPOCH: 5
LOSS: tf.Tensor(91.1253890991211, shape=(), dtype=float64)
EPOCH: 6
LOSS: tf.Tensor(89.54718017578125, shape=(), dtype=float64)
EPOCH: 7
LOSS: tf.Tensor(87.99671173095703, shape=(), dtype=float64)
EPOCH: 8
LOSS: tf.Tensor(86.46151733398438, shape=(), dtype=float64)
EPOCH: 9
LOSS: tf.Tensor(84.95624542236328, shape=(), dtype=float64)
EPOCH: 10
LOSS: tf.Tensor(83.48658752441406, shape=(), dtype=float64)
EPOCH: 11
LOSS: tf.Tensor(82.03563690185547, shape=(), dtype=float64)
EPOCH: 12
LOSS: tf.Tensor(80.6659164428711, shape=(), dtype=float64)
EPOCH: 13
LOSS: tf.Tensor(79.36813354492188, shape=(), dtype=float64)
EPOCH: 14
LOSS: tf.Tensor(78.13981

In [2]:
testModel(test_set[40:50],model)


Prediction: tf.Tensor([[12.6881299]], shape=(1, 1), dtype=float64) True Value: [12.75]
Prediction: tf.Tensor([[8.74254096]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[13.0399277]], shape=(1, 1), dtype=float64) True Value: [15.25]
Prediction: tf.Tensor([[7.98710814]], shape=(1, 1), dtype=float64) True Value: [7.38]
Prediction: tf.Tensor([[9.37725254]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[10.08801944]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[9.37725254]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[11.39966514]], shape=(1, 1), dtype=float64) True Value: [7.75]
Prediction: tf.Tensor([[7.75573463]], shape=(1, 1), dtype=float64) True Value: [8.01]
Prediction: tf.Tensor([[8.30724947]], shape=(1, 1), dtype=float64) True Value: [7.56]


In [3]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, input_dim = 14, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(8, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(82.79515075683594, shape=(), dtype=float64)
EPOCH: 1
LOSS: tf.Tensor(81.28064727783203, shape=(), dtype=float64)
EPOCH: 2
LOSS: tf.Tensor(79.71842956542969, shape=(), dtype=float64)
EPOCH: 3
LOSS: tf.Tensor(78.1761474609375, shape=(), dtype=float64)
EPOCH: 4
LOSS: tf.Tensor(76.62864685058594, shape=(), dtype=float64)
EPOCH: 5
LOSS: tf.Tensor(75.12846374511719, shape=(), dtype=float64)
EPOCH: 6
LOSS: tf.Tensor(73.70658111572266, shape=(), dtype=float64)
EPOCH: 7
LOSS: tf.Tensor(72.33892822265625, shape=(), dtype=float64)
EPOCH: 8
LOSS: tf.Tensor(70.998046875, shape=(), dtype=float64)
EPOCH: 9
LOSS: tf.Tensor(69.7353286743164, shape=(), dtype=float64)
EPOCH: 10
LOSS: tf.Tensor(68.55937194824219, shape=(), dtype=float64)
EPOCH: 11
LOSS: tf.Tensor(67.50895690917969, shape=(), dtype=float64)
EPOCH: 12
LOSS: tf.Tensor(66.60254669189453, shape=(), dtype=float64)
EPOCH: 13
LOSS: tf.Tensor(65.80220031738281, shape=(), dtype=float64)
EPOCH: 14
LOSS: tf.Tensor(65.09441375

In [5]:
testModel(test_set[600:610],model)

Prediction: tf.Tensor([[8.82704445]], shape=(1, 1), dtype=float64) True Value: [8.75]
Prediction: tf.Tensor([[7.79627889]], shape=(1, 1), dtype=float64) True Value: [7.78]
Prediction: tf.Tensor([[5.49443908]], shape=(1, 1), dtype=float64) True Value: [1.18]
Prediction: tf.Tensor([[1.82435009]], shape=(1, 1), dtype=float64) True Value: [3.5]
Prediction: tf.Tensor([[11.44677535]], shape=(1, 1), dtype=float64) True Value: [12.15]
Prediction: tf.Tensor([[2.45036944]], shape=(1, 1), dtype=float64) True Value: [3.1]
Prediction: tf.Tensor([[1.72569661]], shape=(1, 1), dtype=float64) True Value: [3.2]
Prediction: tf.Tensor([[2.35767089]], shape=(1, 1), dtype=float64) True Value: [8.65]
Prediction: tf.Tensor([[7.69820214]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[9.29198868]], shape=(1, 1), dtype=float64) True Value: [8.]
