In [23]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim = 30),
    tf.keras.layers.Dense(32),
    tf.keras.layers.Dense(1)
])


In [24]:
for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)
    

EPOCH: 0
LOSS: tf.Tensor(40.13083267211914, shape=(), dtype=float64)
LOSS: tf.Tensor(39.36677169799805, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(35.93070602416992, shape=(), dtype=float64)
LOSS: tf.Tensor(35.62958526611328, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(32.81915283203125, shape=(), dtype=float64)
LOSS: tf.Tensor(33.04022979736328, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(30.71225929260254, shape=(), dtype=float64)
LOSS: tf.Tensor(31.20697021484375, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(29.320289611816406, shape=(), dtype=float64)
LOSS: tf.Tensor(30.06482696533203, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(28.469141006469727, shape=(), dtype=float64)
LOSS: tf.Tensor(29.344009399414062, shape=(), dty

LOSS: tf.Tensor(25.15103530883789, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 47
LOSS: tf.Tensor(25.670011520385742, shape=(), dtype=float64)
LOSS: tf.Tensor(25.151363372802734, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 48
LOSS: tf.Tensor(25.669233322143555, shape=(), dtype=float64)
LOSS: tf.Tensor(25.151697158813477, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 49
LOSS: tf.Tensor(25.668304443359375, shape=(), dtype=float64)
LOSS: tf.Tensor(25.152217864990234, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 50
LOSS: tf.Tensor(25.667499542236328, shape=(), dtype=float64)
LOSS: tf.Tensor(25.152591705322266, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 51
LOSS: tf.Tensor(25.666595458984375, shape=(), dtype=float64)
LOSS: tf.Tensor(25.152767181396484, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 170

LOSS: tf.Tensor(25.16716766357422, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 93
LOSS: tf.Tensor(25.6535701751709, shape=(), dtype=float64)
LOSS: tf.Tensor(25.167430877685547, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 94
LOSS: tf.Tensor(25.653501510620117, shape=(), dtype=float64)
LOSS: tf.Tensor(25.167438507080078, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 95
LOSS: tf.Tensor(25.653549194335938, shape=(), dtype=float64)
LOSS: tf.Tensor(25.167530059814453, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 96
LOSS: tf.Tensor(25.653419494628906, shape=(), dtype=float64)
LOSS: tf.Tensor(25.167621612548828, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 97
LOSS: tf.Tensor(25.653274536132812, shape=(), dtype=float64)
LOSS: tf.Tensor(25.16765785217285, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
E

In [25]:
testModel(test_set[1000:1010],model)


Prediction: tf.Tensor([[1.50302279]], shape=(1, 1), dtype=float64) True Value: [5.75]
Prediction: tf.Tensor([[0.45599938]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[4.7060464]], shape=(1, 1), dtype=float64) True Value: [6.97]
Prediction: tf.Tensor([[9.02941891]], shape=(1, 1), dtype=float64) True Value: [6.81]
Prediction: tf.Tensor([[6.4425716]], shape=(1, 1), dtype=float64) True Value: [7.25]
Prediction: tf.Tensor([[4.85942715]], shape=(1, 1), dtype=float64) True Value: [0.81]
Prediction: tf.Tensor([[0.65234297]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[3.37363413]], shape=(1, 1), dtype=float64) True Value: [8.17]
Prediction: tf.Tensor([[7.16658932]], shape=(1, 1), dtype=float64) True Value: [6.75]
Prediction: tf.Tensor([[2.10895126]], shape=(1, 1), dtype=float64) True Value: [7.44]
Mean Absolute Error: tf.Tensor([[2.52395516]], shape=(1, 1), dtype=float64)


In [26]:
#same Deep NN, adding activation functions
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim = 30, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(50):
    print("EPOCH: "+str(i))
    train_epoch(model)
    

EPOCH: 0
LOSS: tf.Tensor(28.152667999267578, shape=(), dtype=float64)
LOSS: tf.Tensor(29.531810760498047, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(28.15983772277832, shape=(), dtype=float64)
LOSS: tf.Tensor(29.255138397216797, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(27.979185104370117, shape=(), dtype=float64)
LOSS: tf.Tensor(28.874813079833984, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(27.770465850830078, shape=(), dtype=float64)
LOSS: tf.Tensor(28.507427215576172, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(27.58604621887207, shape=(), dtype=float64)
LOSS: tf.Tensor(28.195770263671875, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(27.425508499145508, shape=(), dtype=float64)
LOSS: tf.Tensor(27.951303482055664, shape=

LOSS: tf.Tensor(26.234546661376953, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 47
LOSS: tf.Tensor(26.11827278137207, shape=(), dtype=float64)
LOSS: tf.Tensor(26.223114013671875, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 48
LOSS: tf.Tensor(26.112384796142578, shape=(), dtype=float64)
LOSS: tf.Tensor(26.211462020874023, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 49
LOSS: tf.Tensor(26.107074737548828, shape=(), dtype=float64)
LOSS: tf.Tensor(26.200374603271484, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708


In [27]:
testModel(test_set[1000:1010],model)

Prediction: tf.Tensor([[1.21921032]], shape=(1, 1), dtype=float64) True Value: [5.75]
Prediction: tf.Tensor([[0.43395004]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[4.40820404]], shape=(1, 1), dtype=float64) True Value: [6.97]
Prediction: tf.Tensor([[9.30384165]], shape=(1, 1), dtype=float64) True Value: [6.81]
Prediction: tf.Tensor([[6.5404818]], shape=(1, 1), dtype=float64) True Value: [7.25]
Prediction: tf.Tensor([[5.35834372]], shape=(1, 1), dtype=float64) True Value: [0.81]
Prediction: tf.Tensor([[0.53810222]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[3.88180896]], shape=(1, 1), dtype=float64) True Value: [8.17]
Prediction: tf.Tensor([[6.86387053]], shape=(1, 1), dtype=float64) True Value: [6.75]
Prediction: tf.Tensor([[1.51246617]], shape=(1, 1), dtype=float64) True Value: [7.44]
Mean Absolute Error: tf.Tensor([[2.61459369]], shape=(1, 1), dtype=float64)


In [28]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, input_dim = 30, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(50):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(43.554786682128906, shape=(), dtype=float64)
LOSS: tf.Tensor(52.454681396484375, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(35.604347229003906, shape=(), dtype=float64)
LOSS: tf.Tensor(44.170166015625, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(31.466697692871094, shape=(), dtype=float64)
LOSS: tf.Tensor(38.082374572753906, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(28.97053337097168, shape=(), dtype=float64)
LOSS: tf.Tensor(33.541465759277344, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(27.521373748779297, shape=(), dtype=float64)
LOSS: tf.Tensor(30.651113510131836, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(26.802677154541016, shape=(), dtype=float64)
LOSS: tf.Tensor(29.09297752380371, shape=(),

LOSS: tf.Tensor(25.947139739990234, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 47
LOSS: tf.Tensor(25.914949417114258, shape=(), dtype=float64)
LOSS: tf.Tensor(25.935718536376953, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 48
LOSS: tf.Tensor(25.911773681640625, shape=(), dtype=float64)
LOSS: tf.Tensor(25.92409896850586, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 49
LOSS: tf.Tensor(25.90899085998535, shape=(), dtype=float64)
LOSS: tf.Tensor(25.913503646850586, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708


In [30]:
testModel(test_set[40:60],model)


Prediction: tf.Tensor([[7.20278144]], shape=(1, 1), dtype=float64) True Value: [1.]
Prediction: tf.Tensor([[7.83212153]], shape=(1, 1), dtype=float64) True Value: [6.25]
Prediction: tf.Tensor([[6.56961075]], shape=(1, 1), dtype=float64) True Value: [10.02]
Prediction: tf.Tensor([[4.48893334]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[6.05668294]], shape=(1, 1), dtype=float64) True Value: [9.33]
Prediction: tf.Tensor([[8.50387062]], shape=(1, 1), dtype=float64) True Value: [6.52]
Prediction: tf.Tensor([[2.49566947]], shape=(1, 1), dtype=float64) True Value: [9.5]
Prediction: tf.Tensor([[1.33524109]], shape=(1, 1), dtype=float64) True Value: [2.]
Prediction: tf.Tensor([[7.66995896]], shape=(1, 1), dtype=float64) True Value: [7.63]
Prediction: tf.Tensor([[6.65665521]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[12.5636187]], shape=(1, 1), dtype=float64) True Value: [15.]
Prediction: tf.Tensor([[5.57948689]], shape=(1, 1), dtype=float

In [31]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, input_dim = 30, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(8, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(50):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(43.123817443847656, shape=(), dtype=float64)
LOSS: tf.Tensor(43.031192779541016, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(33.004966735839844, shape=(), dtype=float64)
LOSS: tf.Tensor(34.205413818359375, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(29.052303314208984, shape=(), dtype=float64)
LOSS: tf.Tensor(29.816654205322266, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(27.461576461791992, shape=(), dtype=float64)
LOSS: tf.Tensor(28.16350555419922, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(26.971614837646484, shape=(), dtype=float64)
LOSS: tf.Tensor(27.568241119384766, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(26.765567779541016, shape=(), dtype=float64)
LOSS: tf.Tensor(27.304828643798828, shape

LOSS: tf.Tensor(25.941930770874023, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 47
LOSS: tf.Tensor(26.09450912475586, shape=(), dtype=float64)
LOSS: tf.Tensor(25.932476043701172, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 48
LOSS: tf.Tensor(26.09146499633789, shape=(), dtype=float64)
LOSS: tf.Tensor(25.922334671020508, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 49
LOSS: tf.Tensor(26.087909698486328, shape=(), dtype=float64)
LOSS: tf.Tensor(25.913665771484375, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708


In [46]:
%run basic_model.py

testModel(test_set[100:150],model)

Prediction: tf.Tensor([[4.31184012]], shape=(1, 1), dtype=float64) True Value: [3.92]
Prediction: tf.Tensor([[6.911432]], shape=(1, 1), dtype=float64) True Value: [5.75]
Prediction: tf.Tensor([[7.93234753]], shape=(1, 1), dtype=float64) True Value: [8.7]
Prediction: tf.Tensor([[6.95077504]], shape=(1, 1), dtype=float64) True Value: [11.67]
Prediction: tf.Tensor([[10.00896197]], shape=(1, 1), dtype=float64) True Value: [6.5]
Prediction: tf.Tensor([[6.24702922]], shape=(1, 1), dtype=float64) True Value: [1.02]
Prediction: tf.Tensor([[6.90544975]], shape=(1, 1), dtype=float64) True Value: [7.63]
Prediction: tf.Tensor([[7.65869561]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[7.21049749]], shape=(1, 1), dtype=float64) True Value: [1.2]
Prediction: tf.Tensor([[7.78124488]], shape=(1, 1), dtype=float64) True Value: [7.38]
Prediction: tf.Tensor([[7.29525372]], shape=(1, 1), dtype=float64) True Value: [12.24]
Prediction: tf.Tensor([[6.60914075]], shape=(1, 1), dtype