In [6]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(32),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch()


EPOCH: 0
LOSS: tf.Tensor(94.02095031738281, shape=(), dtype=float64)
EPOCH: 1
LOSS: tf.Tensor(93.45323181152344, shape=(), dtype=float64)
EPOCH: 2
LOSS: tf.Tensor(92.86457824707031, shape=(), dtype=float64)
EPOCH: 3
LOSS: tf.Tensor(92.26669311523438, shape=(), dtype=float64)
EPOCH: 4
LOSS: tf.Tensor(91.65855407714844, shape=(), dtype=float64)
EPOCH: 5
LOSS: tf.Tensor(91.04164123535156, shape=(), dtype=float64)
EPOCH: 6
LOSS: tf.Tensor(90.41934204101562, shape=(), dtype=float64)
EPOCH: 7
LOSS: tf.Tensor(89.78291320800781, shape=(), dtype=float64)
EPOCH: 8
LOSS: tf.Tensor(89.12913513183594, shape=(), dtype=float64)
EPOCH: 9
LOSS: tf.Tensor(88.45684814453125, shape=(), dtype=float64)
EPOCH: 10
LOSS: tf.Tensor(87.7689208984375, shape=(), dtype=float64)
EPOCH: 11
LOSS: tf.Tensor(87.0560302734375, shape=(), dtype=float64)
EPOCH: 12
LOSS: tf.Tensor(86.31688690185547, shape=(), dtype=float64)
EPOCH: 13
LOSS: tf.Tensor(85.55348205566406, shape=(), dtype=float64)
EPOCH: 14
LOSS: tf.Tensor(84.768

In [7]:
testModel(test_set[1000:1010])


Prediction: tf.Tensor([[8.19474234]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[6.89234235]], shape=(1, 1), dtype=float64) True Value: [2.]
Prediction: tf.Tensor([[8.27988223]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[9.37949634]], shape=(1, 1), dtype=float64) True Value: [5.21]
Prediction: tf.Tensor([[5.71535886]], shape=(1, 1), dtype=float64) True Value: [6.65]
Prediction: tf.Tensor([[9.36149519]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[5.84217027]], shape=(1, 1), dtype=float64) True Value: [10.]
Prediction: tf.Tensor([[6.86213577]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[7.32432644]], shape=(1, 1), dtype=float64) True Value: [6.68]
Prediction: tf.Tensor([[8.58061516]], shape=(1, 1), dtype=float64) True Value: [7.65]


In [4]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(1)
])

for i in range(60):
    print("EPOCH: "+str(i))
    train_epoch(model)



EPOCH: 0
LOSS: tf.Tensor(93.20196533203125, shape=(), dtype=float64)
EPOCH: 1
LOSS: tf.Tensor(92.9759521484375, shape=(), dtype=float64)
EPOCH: 2
LOSS: tf.Tensor(92.7505874633789, shape=(), dtype=float64)
EPOCH: 3
LOSS: tf.Tensor(92.51652526855469, shape=(), dtype=float64)
EPOCH: 4
LOSS: tf.Tensor(92.270751953125, shape=(), dtype=float64)
EPOCH: 5
LOSS: tf.Tensor(92.02261352539062, shape=(), dtype=float64)
EPOCH: 6
LOSS: tf.Tensor(91.77479553222656, shape=(), dtype=float64)
EPOCH: 7
LOSS: tf.Tensor(91.52754211425781, shape=(), dtype=float64)
EPOCH: 8
LOSS: tf.Tensor(91.27899169921875, shape=(), dtype=float64)
EPOCH: 9
LOSS: tf.Tensor(91.02979278564453, shape=(), dtype=float64)
EPOCH: 10
LOSS: tf.Tensor(90.77983093261719, shape=(), dtype=float64)
EPOCH: 11
LOSS: tf.Tensor(90.51948547363281, shape=(), dtype=float64)
EPOCH: 12
LOSS: tf.Tensor(90.23725891113281, shape=(), dtype=float64)
EPOCH: 13
LOSS: tf.Tensor(89.94038391113281, shape=(), dtype=float64)
EPOCH: 14
LOSS: tf.Tensor(89.63761

In [6]:
testModel(test_set[3000:3010],model)


Prediction: tf.Tensor([[5.08741301]], shape=(1, 1), dtype=float64) True Value: [3.]
Prediction: tf.Tensor([[6.91965836]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[7.05762175]], shape=(1, 1), dtype=float64) True Value: [7.25]
Prediction: tf.Tensor([[6.9725497]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[4.65318935]], shape=(1, 1), dtype=float64) True Value: [6.]
Prediction: tf.Tensor([[1.27637474]], shape=(1, 1), dtype=float64) True Value: [3.07]
Prediction: tf.Tensor([[2.46808374]], shape=(1, 1), dtype=float64) True Value: [4.3]
Prediction: tf.Tensor([[7.02497134]], shape=(1, 1), dtype=float64) True Value: [8.3]
Prediction: tf.Tensor([[7.6445093]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[4.22587117]], shape=(1, 1), dtype=float64) True Value: [15.]


In [8]:
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(94.06441497802734, shape=(), dtype=float64)
EPOCH: 1
LOSS: tf.Tensor(91.30718994140625, shape=(), dtype=float64)
EPOCH: 2
LOSS: tf.Tensor(89.95597839355469, shape=(), dtype=float64)
EPOCH: 3
LOSS: tf.Tensor(88.73707580566406, shape=(), dtype=float64)
EPOCH: 4
LOSS: tf.Tensor(87.56375122070312, shape=(), dtype=float64)
EPOCH: 5
LOSS: tf.Tensor(86.38874053955078, shape=(), dtype=float64)
EPOCH: 6
LOSS: tf.Tensor(85.14790344238281, shape=(), dtype=float64)
EPOCH: 7
LOSS: tf.Tensor(83.74628448486328, shape=(), dtype=float64)
EPOCH: 8
LOSS: tf.Tensor(82.15812683105469, shape=(), dtype=float64)
EPOCH: 9
LOSS: tf.Tensor(80.45352172851562, shape=(), dtype=float64)
EPOCH: 10
LOSS: tf.Tensor(78.57157135009766, shape=(), dtype=float64)
EPOCH: 11
LOSS: tf.Tensor(76.48593139648438, shape=(), dtype=float64)
EPOCH: 12
LOSS: tf.Tensor(74.33110046386719, shape=(), dtype=float64)
EPOCH: 13
LOSS: tf.Tensor(72.12010955810547, shape=(), dtype=float64)
EPOCH: 14
LOSS: tf.Tensor(69.9

In [10]:
testModel(test_set[500:510],model)

Prediction: tf.Tensor([[8.4625896]], shape=(1, 1), dtype=float64) True Value: [0.15]
Prediction: tf.Tensor([[7.30666343]], shape=(1, 1), dtype=float64) True Value: [2.87]
Prediction: tf.Tensor([[4.66953487]], shape=(1, 1), dtype=float64) True Value: [9.73]
Prediction: tf.Tensor([[8.90090388]], shape=(1, 1), dtype=float64) True Value: [7.45]
Prediction: tf.Tensor([[10.71923327]], shape=(1, 1), dtype=float64) True Value: [8.75]
Prediction: tf.Tensor([[10.24542748]], shape=(1, 1), dtype=float64) True Value: [8.88]
Prediction: tf.Tensor([[8.74743472]], shape=(1, 1), dtype=float64) True Value: [6.15]
Prediction: tf.Tensor([[12.16116431]], shape=(1, 1), dtype=float64) True Value: [11.67]
Prediction: tf.Tensor([[5.22062572]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[9.48226406]], shape=(1, 1), dtype=float64) True Value: [8.]
