In [2]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(32),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)



EPOCH: 0
LOSS: tf.Tensor(32.539127349853516, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 1
LOSS: tf.Tensor(32.369258880615234, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 2
LOSS: tf.Tensor(32.219512939453125, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 3
LOSS: tf.Tensor(32.07324981689453, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 4
LOSS: tf.Tensor(31.927810668945312, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 5
LOSS: tf.Tensor(31.78214454650879, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 6
LOSS: tf.Tensor(31.63494110107422, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 7
LOSS: tf.Tensor(31.485580444335938, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 8
LOSS: tf.Tensor(31.33335304260254, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 9
LOSS: tf.Tensor(31.177736282348633, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 10
LOSS: tf.Tensor(31.01822853088379, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 11
LOSS: tf.Tensor(30.854148864746094, shape=(), dtype=float64)
NAN Coun

NAN Count: 66
EPOCH: 98
LOSS: tf.Tensor(25.94784164428711, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 99
LOSS: tf.Tensor(25.94698715209961, shape=(), dtype=float64)
NAN Count: 66


In [3]:
testModel(test_set[1000:1010],model)


Prediction: tf.Tensor([[2.1935229]], shape=(1, 1), dtype=float64) True Value: [4.5]
Prediction: tf.Tensor([[6.66522039]], shape=(1, 1), dtype=float64) True Value: [11.04]
Prediction: tf.Tensor([[8.78438926]], shape=(1, 1), dtype=float64) True Value: [13.08]
Prediction: tf.Tensor([[8.49771486]], shape=(1, 1), dtype=float64) True Value: [12.13]
Prediction: tf.Tensor([[6.49995338]], shape=(1, 1), dtype=float64) True Value: [4.83]
Prediction: tf.Tensor([[7.11884158]], shape=(1, 1), dtype=float64) True Value: [4.5]
Prediction: tf.Tensor([[4.5075136]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[5.54779637]], shape=(1, 1), dtype=float64) True Value: [7.83]
Prediction: tf.Tensor([[4.94059628]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[5.12756676]], shape=(1, 1), dtype=float64) True Value: [12.]


In [4]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(1)
])

for i in range(60):
    print("EPOCH: "+str(i))
    train_epoch(model)




EPOCH: 0
LOSS: tf.Tensor(32.491668701171875, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 1
LOSS: tf.Tensor(32.41705322265625, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 2
LOSS: tf.Tensor(32.350799560546875, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 3
LOSS: tf.Tensor(32.285888671875, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 4
LOSS: tf.Tensor(32.22257995605469, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 5
LOSS: tf.Tensor(32.15979766845703, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 6
LOSS: tf.Tensor(32.09716033935547, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 7
LOSS: tf.Tensor(32.0352668762207, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 8
LOSS: tf.Tensor(31.97321891784668, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 9
LOSS: tf.Tensor(31.910139083862305, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 10
LOSS: tf.Tensor(31.847270965576172, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 11
LOSS: tf.Tensor(31.784591674804688, shape=(), dtype=float64)
NAN Count: 66

In [5]:
testModel(test_set[3000:3010],model)


Prediction: tf.Tensor([[1.79637745]], shape=(1, 1), dtype=float64) True Value: [7.54]
Prediction: tf.Tensor([[4.33481029]], shape=(1, 1), dtype=float64) True Value: [3.62]
Prediction: tf.Tensor([[8.53197942]], shape=(1, 1), dtype=float64) True Value: [12.57]
Prediction: tf.Tensor([[5.97354316]], shape=(1, 1), dtype=float64) True Value: [6.25]
Prediction: tf.Tensor([[2.94561217]], shape=(1, 1), dtype=float64) True Value: [6.75]
Prediction: tf.Tensor([[2.33304467]], shape=(1, 1), dtype=float64) True Value: [6.5]
Prediction: tf.Tensor([[5.21302039]], shape=(1, 1), dtype=float64) True Value: [9.33]
Prediction: tf.Tensor([[5.81464485]], shape=(1, 1), dtype=float64) True Value: [7.72]
Prediction: tf.Tensor([[7.27538186]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[3.77470147]], shape=(1, 1), dtype=float64) True Value: [5.25]


In [6]:
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(32.31474685668945, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 1
LOSS: tf.Tensor(31.86777114868164, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 2
LOSS: tf.Tensor(31.646896362304688, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 3
LOSS: tf.Tensor(31.452089309692383, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 4
LOSS: tf.Tensor(31.258398056030273, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 5
LOSS: tf.Tensor(31.051376342773438, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 6
LOSS: tf.Tensor(30.827497482299805, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 7
LOSS: tf.Tensor(30.572635650634766, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 8
LOSS: tf.Tensor(30.28376007080078, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 9
LOSS: tf.Tensor(29.954347610473633, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 10
LOSS: tf.Tensor(29.56238555908203, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 11
LOSS: tf.Tensor(29.093761444091797, shape=(), dtype=float64)
NAN Coun

NAN Count: 66
EPOCH: 97
LOSS: tf.Tensor(25.90799331665039, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 98
LOSS: tf.Tensor(25.907028198242188, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 99
LOSS: tf.Tensor(25.906009674072266, shape=(), dtype=float64)
NAN Count: 66


In [8]:
testModel(test_set[500:550],model)

Prediction: tf.Tensor([[7.95998815]], shape=(1, 1), dtype=float64) True Value: [8.08]
Prediction: tf.Tensor([[8.64776942]], shape=(1, 1), dtype=float64) True Value: [9.]
Prediction: tf.Tensor([[6.9473533]], shape=(1, 1), dtype=float64) True Value: [6.75]
Prediction: tf.Tensor([[7.53747445]], shape=(1, 1), dtype=float64) True Value: [7.53]
Prediction: tf.Tensor([[4.88074409]], shape=(1, 1), dtype=float64) True Value: [6.78]
Prediction: tf.Tensor([[6.33679923]], shape=(1, 1), dtype=float64) True Value: [4.5]
Prediction: tf.Tensor([[8.68711586]], shape=(1, 1), dtype=float64) True Value: [5.5]
Prediction: tf.Tensor([[9.84767205]], shape=(1, 1), dtype=float64) True Value: [11.25]
Prediction: tf.Tensor([[4.88176271]], shape=(1, 1), dtype=float64) True Value: [13.]
Prediction: tf.Tensor([[6.35252232]], shape=(1, 1), dtype=float64) True Value: [7.67]
Prediction: tf.Tensor([[1.1989038]], shape=(1, 1), dtype=float64) True Value: [1.5]
Prediction: tf.Tensor([[7.51829869]], shape=(1, 1), dtype=flo