In [1]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim = 30),
    tf.keras.layers.Dense(32),
    tf.keras.layers.Dense(1)
])


In [2]:
for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)
    

EPOCH: 0
LOSS: tf.Tensor(47.02888488769531, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 1
LOSS: tf.Tensor(45.63462448120117, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 2
LOSS: tf.Tensor(44.35057830810547, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 3
LOSS: tf.Tensor(43.160400390625, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 4
LOSS: tf.Tensor(42.07221984863281, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 5
LOSS: tf.Tensor(41.05571746826172, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 6
LOSS: tf.Tensor(40.11796951293945, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 7
LOSS: tf.Tensor(39.242984771728516, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 8
LOSS: tf.Tensor(38.43272399902344, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 9
LOSS: tf.Tensor(37.667015075683594, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 10
LOSS: tf.Tensor(36.9291877746582, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 11
LOSS: tf.Tensor(36.227256774902344, shape=(), dtype=float64)
NAN Count: 66
EP

NAN Count: 66
EPOCH: 98
LOSS: tf.Tensor(26.881826400756836, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 99
LOSS: tf.Tensor(26.871252059936523, shape=(), dtype=float64)
NAN Count: 66


In [3]:
testModel(test_set[1000:1010],model)


Prediction: tf.Tensor([[2.34653703]], shape=(1, 1), dtype=float64) True Value: [4.5]
Prediction: tf.Tensor([[6.61882589]], shape=(1, 1), dtype=float64) True Value: [11.04]
Prediction: tf.Tensor([[7.55414344]], shape=(1, 1), dtype=float64) True Value: [13.08]
Prediction: tf.Tensor([[7.44688195]], shape=(1, 1), dtype=float64) True Value: [12.13]
Prediction: tf.Tensor([[5.48533576]], shape=(1, 1), dtype=float64) True Value: [4.83]
Prediction: tf.Tensor([[6.82194699]], shape=(1, 1), dtype=float64) True Value: [4.5]
Prediction: tf.Tensor([[4.90707321]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[5.32673267]], shape=(1, 1), dtype=float64) True Value: [7.83]
Prediction: tf.Tensor([[4.19588234]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[4.73329032]], shape=(1, 1), dtype=float64) True Value: [12.]


In [4]:
#same Deep NN, adding activation functions
model = tf.keras.Sequential([
    tf.keras.layers.Dense(64, input_dim = 30, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)
    

EPOCH: 0
LOSS: tf.Tensor(57.61968994140625, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 1
LOSS: tf.Tensor(50.39934539794922, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 2
LOSS: tf.Tensor(47.21853256225586, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 3
LOSS: tf.Tensor(44.75415802001953, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 4
LOSS: tf.Tensor(42.72181701660156, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 5
LOSS: tf.Tensor(41.019622802734375, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 6
LOSS: tf.Tensor(39.64374542236328, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 7
LOSS: tf.Tensor(38.47206115722656, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 8
LOSS: tf.Tensor(37.434326171875, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 9
LOSS: tf.Tensor(36.493492126464844, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 10
LOSS: tf.Tensor(35.614662170410156, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 11
LOSS: tf.Tensor(34.82938766479492, shape=(), dtype=float64)
NAN Count: 66
E

NAN Count: 66
EPOCH: 98
LOSS: tf.Tensor(27.05691909790039, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 99
LOSS: tf.Tensor(27.047407150268555, shape=(), dtype=float64)
NAN Count: 66


In [5]:
testModel(test_set[1000:1010],model)

Prediction: tf.Tensor([[2.64750944]], shape=(1, 1), dtype=float64) True Value: [4.5]
Prediction: tf.Tensor([[8.52750801]], shape=(1, 1), dtype=float64) True Value: [11.04]
Prediction: tf.Tensor([[6.86414491]], shape=(1, 1), dtype=float64) True Value: [13.08]
Prediction: tf.Tensor([[7.32914071]], shape=(1, 1), dtype=float64) True Value: [12.13]
Prediction: tf.Tensor([[5.67861159]], shape=(1, 1), dtype=float64) True Value: [4.83]
Prediction: tf.Tensor([[8.23389023]], shape=(1, 1), dtype=float64) True Value: [4.5]
Prediction: tf.Tensor([[3.92016666]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[5.06394833]], shape=(1, 1), dtype=float64) True Value: [7.83]
Prediction: tf.Tensor([[5.65352269]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[6.11459458]], shape=(1, 1), dtype=float64) True Value: [12.]


In [6]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, input_dim = 30, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)


EPOCH: 0
LOSS: tf.Tensor(26.43655014038086, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 1
LOSS: tf.Tensor(26.40892791748047, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 2
LOSS: tf.Tensor(26.396556854248047, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 3
LOSS: tf.Tensor(26.39505958557129, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 4
LOSS: tf.Tensor(26.395977020263672, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 5
LOSS: tf.Tensor(26.397483825683594, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 6
LOSS: tf.Tensor(26.396543502807617, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 7
LOSS: tf.Tensor(26.39446258544922, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 8
LOSS: tf.Tensor(26.391576766967773, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 9
LOSS: tf.Tensor(26.387928009033203, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 10
LOSS: tf.Tensor(26.383867263793945, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 11
LOSS: tf.Tensor(26.37887191772461, shape=(), dtype=float64)
NAN Coun

NAN Count: 66
EPOCH: 98
LOSS: tf.Tensor(26.180622100830078, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 99
LOSS: tf.Tensor(26.180837631225586, shape=(), dtype=float64)
NAN Count: 66


In [7]:
testModel(test_set[40:50],model)


Prediction: tf.Tensor([[1.57175481]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[0.25589955]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[6.02414701]], shape=(1, 1), dtype=float64) True Value: [7.75]
Prediction: tf.Tensor([[1.96772602]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[4.83427259]], shape=(1, 1), dtype=float64) True Value: [3.83]
Prediction: tf.Tensor([[6.52469045]], shape=(1, 1), dtype=float64) True Value: [7.67]
Prediction: tf.Tensor([[9.17454824]], shape=(1, 1), dtype=float64) True Value: [8.33]
Prediction: tf.Tensor([[9.10957238]], shape=(1, 1), dtype=float64) True Value: [8.42]
Prediction: tf.Tensor([[3.13900626]], shape=(1, 1), dtype=float64) True Value: [3.88]
Prediction: tf.Tensor([[7.37543508]], shape=(1, 1), dtype=float64) True Value: [8.]


In [8]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.Dense(128, input_dim = 30, activation = 'relu'),
    tf.keras.layers.Dense(64, activation = 'relu'),
    tf.keras.layers.Dense(32, activation = 'relu'),
    tf.keras.layers.Dense(8, activation = 'relu'),
    tf.keras.layers.Dense(1)
])

for i in range(100):
    print("EPOCH: "+str(i))
    train_epoch(model)


EPOCH: 0
LOSS: tf.Tensor(37.77500534057617, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 1
LOSS: tf.Tensor(36.106319427490234, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 2
LOSS: tf.Tensor(34.90996551513672, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 3
LOSS: tf.Tensor(34.015533447265625, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 4
LOSS: tf.Tensor(33.36235809326172, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 5
LOSS: tf.Tensor(32.81044387817383, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 6
LOSS: tf.Tensor(32.31167984008789, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 7
LOSS: tf.Tensor(31.895090103149414, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 8
LOSS: tf.Tensor(31.53105354309082, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 9
LOSS: tf.Tensor(31.196714401245117, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 10
LOSS: tf.Tensor(30.882661819458008, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 11
LOSS: tf.Tensor(30.58693504333496, shape=(), dtype=float64)
NAN Count:

NAN Count: 66
EPOCH: 98
LOSS: tf.Tensor(26.446392059326172, shape=(), dtype=float64)
NAN Count: 66
EPOCH: 99
LOSS: tf.Tensor(26.443084716796875, shape=(), dtype=float64)
NAN Count: 66


In [9]:
testModel(test_set[600:610],model)

Prediction: tf.Tensor([[0.10001318]], shape=(1, 1), dtype=float64) True Value: [0.2]
Prediction: tf.Tensor([[5.55167523]], shape=(1, 1), dtype=float64) True Value: [7.75]
Prediction: tf.Tensor([[4.10812905]], shape=(1, 1), dtype=float64) True Value: [7.75]
Prediction: tf.Tensor([[6.75482931]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[5.95597716]], shape=(1, 1), dtype=float64) True Value: [8.25]
Prediction: tf.Tensor([[7.88161494]], shape=(1, 1), dtype=float64) True Value: [8.25]
Prediction: tf.Tensor([[6.52676818]], shape=(1, 1), dtype=float64) True Value: [3.25]
Prediction: tf.Tensor([[3.34470568]], shape=(1, 1), dtype=float64) True Value: [3.12]
Prediction: tf.Tensor([[3.85992246]], shape=(1, 1), dtype=float64) True Value: [11.5]
Prediction: tf.Tensor([[7.79035529]], shape=(1, 1), dtype=float64) True Value: [7.]
