In [11]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(64),
    tf.keras.layers.Dense(32),
    tf.keras.layers.Dense(1)
])

for i in range(50):
    print("EPOCH: "+str(i))
    train_epoch(model)


EPOCH: 0
LOSS: tf.Tensor(32.27848434448242, shape=(), dtype=float64)
LOSS: tf.Tensor(38.563873291015625, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(31.490625381469727, shape=(), dtype=float64)
LOSS: tf.Tensor(36.6275634765625, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(30.389556884765625, shape=(), dtype=float64)
LOSS: tf.Tensor(33.62579345703125, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(28.761112213134766, shape=(), dtype=float64)
LOSS: tf.Tensor(29.165769577026367, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(26.916276931762695, shape=(), dtype=float64)
LOSS: tf.Tensor(26.32807731628418, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(26.218212127685547, shape=(), dtype=float64)
LOSS: tf.Tensor(25.71869468688965, shape=(), 

LOSS: tf.Tensor(24.919023513793945, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 47
LOSS: tf.Tensor(25.763504028320312, shape=(), dtype=float64)
LOSS: tf.Tensor(24.917804718017578, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 48
LOSS: tf.Tensor(25.763530731201172, shape=(), dtype=float64)
LOSS: tf.Tensor(24.9160099029541, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 49
LOSS: tf.Tensor(25.763521194458008, shape=(), dtype=float64)
LOSS: tf.Tensor(24.91435432434082, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708


In [13]:

testModel(test_set[1000:1020],model)


Prediction: tf.Tensor([[1.46965375]], shape=(1, 1), dtype=float64) True Value: [5.75]
Prediction: tf.Tensor([[0.43842798]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[4.68595784]], shape=(1, 1), dtype=float64) True Value: [6.97]
Prediction: tf.Tensor([[8.93841772]], shape=(1, 1), dtype=float64) True Value: [6.81]
Prediction: tf.Tensor([[6.33547733]], shape=(1, 1), dtype=float64) True Value: [7.25]
Prediction: tf.Tensor([[4.79168849]], shape=(1, 1), dtype=float64) True Value: [0.81]
Prediction: tf.Tensor([[0.6163024]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[3.30472761]], shape=(1, 1), dtype=float64) True Value: [8.17]
Prediction: tf.Tensor([[7.19466375]], shape=(1, 1), dtype=float64) True Value: [6.75]
Prediction: tf.Tensor([[2.04159134]], shape=(1, 1), dtype=float64) True Value: [7.44]
Prediction: tf.Tensor([[6.2609765]], shape=(1, 1), dtype=float64) True Value: [9.4]
Prediction: tf.Tensor([[6.66071031]], shape=(1, 1), dtype=flo

In [14]:
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(1)
])

for i in range(25):
    print("EPOCH: "+str(i))
    train_epoch(model)



EPOCH: 0
LOSS: tf.Tensor(32.06459426879883, shape=(), dtype=float64)
LOSS: tf.Tensor(38.2200927734375, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(31.63064956665039, shape=(), dtype=float64)
LOSS: tf.Tensor(37.23631286621094, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(31.126020431518555, shape=(), dtype=float64)
LOSS: tf.Tensor(36.165279388427734, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(30.55913543701172, shape=(), dtype=float64)
LOSS: tf.Tensor(35.004817962646484, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(29.919187545776367, shape=(), dtype=float64)
LOSS: tf.Tensor(33.67300033569336, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(29.20553207397461, shape=(), dtype=float64)
LOSS: tf.Tensor(32.16032409667969, shape=(), dty

In [17]:
testModel(test_set[3050:3070],model)


Prediction: tf.Tensor([[7.73309243]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[1.5550522]], shape=(1, 1), dtype=float64) True Value: [2.25]
Prediction: tf.Tensor([[7.0954532]], shape=(1, 1), dtype=float64) True Value: [9.47]
Prediction: tf.Tensor([[0.54174974]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[8.04449912]], shape=(1, 1), dtype=float64) True Value: [8.25]
Prediction: tf.Tensor([[0.05037063]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[7.27285686]], shape=(1, 1), dtype=float64) True Value: [1.75]
Prediction: tf.Tensor([[2.41160879]], shape=(1, 1), dtype=float64) True Value: [5.53]
Prediction: tf.Tensor([[0.34965037]], shape=(1, 1), dtype=float64) True Value: [1.5]
Prediction: tf.Tensor([[5.21920746]], shape=(1, 1), dtype=float64) True Value: [6.9]
Prediction: tf.Tensor([[6.43627515]], shape=(1, 1), dtype=float64) True Value: [7.75]
Prediction: tf.Tensor([[6.83710784]], shape=(1, 1), dtype=float6

In [18]:
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(64,activation='relu'),
    tf.keras.layers.Dense(32,activation='relu'),
    tf.keras.layers.Dense(1)
])

for i in range(40):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(32.37602233886719, shape=(), dtype=float64)
LOSS: tf.Tensor(37.39625930786133, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(30.909290313720703, shape=(), dtype=float64)
LOSS: tf.Tensor(33.07654571533203, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(27.550748825073242, shape=(), dtype=float64)
LOSS: tf.Tensor(25.565439224243164, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(26.142818450927734, shape=(), dtype=float64)
LOSS: tf.Tensor(25.29405975341797, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(26.033689498901367, shape=(), dtype=float64)
LOSS: tf.Tensor(25.18844223022461, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(25.980356216430664, shape=(), dtype=float64)
LOSS: tf.Tensor(25.130386352539062, shape=(),

In [19]:
testModel(test_set[500:550],model)

Prediction: tf.Tensor([[8.14094546]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[7.23499372]], shape=(1, 1), dtype=float64) True Value: [8.95]
Prediction: tf.Tensor([[7.1864741]], shape=(1, 1), dtype=float64) True Value: [9.08]
Prediction: tf.Tensor([[8.20528225]], shape=(1, 1), dtype=float64) True Value: [11.5]
Prediction: tf.Tensor([[6.36728521]], shape=(1, 1), dtype=float64) True Value: [7.22]
Prediction: tf.Tensor([[7.84191013]], shape=(1, 1), dtype=float64) True Value: [16.63]
Prediction: tf.Tensor([[7.92310251]], shape=(1, 1), dtype=float64) True Value: [1.]
Prediction: tf.Tensor([[9.44072686]], shape=(1, 1), dtype=float64) True Value: [6.71]
Prediction: tf.Tensor([[8.11716266]], shape=(1, 1), dtype=float64) True Value: [12.]
Prediction: tf.Tensor([[4.67548511]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[10.83489947]], shape=(1, 1), dtype=float64) True Value: [11.5]
Prediction: tf.Tensor([[4.71456348]], shape=(1, 1), dtype=f

In [20]:
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(1)
])

for i in range(10):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(32.400306701660156, shape=(), dtype=float64)
LOSS: tf.Tensor(36.539344787597656, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(29.967365264892578, shape=(), dtype=float64)
LOSS: tf.Tensor(27.33927345275879, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(26.373291015625, shape=(), dtype=float64)
LOSS: tf.Tensor(25.562423706054688, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(26.152973175048828, shape=(), dtype=float64)
LOSS: tf.Tensor(25.37871742248535, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(26.067596435546875, shape=(), dtype=float64)
LOSS: tf.Tensor(25.26541519165039, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(26.01150894165039, shape=(), dtype=float64)
LOSS: tf.Tensor(25.194223403930664, shape=(), d

In [21]:
testModel(test_set[68:81],model)

Prediction: tf.Tensor([[6.59222783]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[6.51506853]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[2.89179334]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[6.75548176]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[0.54034095]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[7.96465876]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[5.06118205]], shape=(1, 1), dtype=float64) True Value: [5.]
Prediction: tf.Tensor([[7.43143013]], shape=(1, 1), dtype=float64) True Value: [8.1]
Prediction: tf.Tensor([[7.31570724]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[6.95109477]], shape=(1, 1), dtype=float64) True Value: [7.65]
Prediction: tf.Tensor([[6.15729686]], shape=(1, 1), dtype=float64) True Value: [2.75]
Prediction: tf.Tensor([[0.02755736]], shape=(1, 1), dtype=float64) 

In [22]:
testModel(test_set[9000:9037],model)


Prediction: tf.Tensor([[0.77782744]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[6.08113639]], shape=(1, 1), dtype=float64) True Value: [9.]
Prediction: tf.Tensor([[6.06292342]], shape=(1, 1), dtype=float64) True Value: [6.5]
Prediction: tf.Tensor([[0.74150942]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[0.85798234]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[4.15642564]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[0.63267308]], shape=(1, 1), dtype=float64) True Value: [0.]
Prediction: tf.Tensor([[5.78257378]], shape=(1, 1), dtype=float64) True Value: [7.5]
Prediction: tf.Tensor([[3.53510274]], shape=(1, 1), dtype=float64) True Value: [7.75]
Prediction: tf.Tensor([[4.48456793]], shape=(1, 1), dtype=float64) True Value: [5.5]
Prediction: tf.Tensor([[3.43352436]], shape=(1, 1), dtype=float64) True Value: [8.5]
Prediction: tf.Tensor([[0.77126215]], shape=(1, 1), dtype=float64) Tru

In [23]:
#changed loss to mean squared error. this should result in better precision
#also no longer multiplying loss by batch size
%run basic_model.py
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(1)
])

for i in range(10):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(2.285938024520874, shape=(), dtype=float64)
LOSS: tf.Tensor(2.909180164337158, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(2.0962464809417725, shape=(), dtype=float64)
LOSS: tf.Tensor(2.119019031524658, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(1.5987236499786377, shape=(), dtype=float64)
LOSS: tf.Tensor(1.8228538036346436, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(1.5811476707458496, shape=(), dtype=float64)
LOSS: tf.Tensor(1.8118759393692017, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(1.5766011476516724, shape=(), dtype=float64)
LOSS: tf.Tensor(1.8068301677703857, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(1.5742286443710327, shape=(), dtype=float64)
LOSS: tf.Tensor(1.8040533065795898, shape=(

In [24]:
testModel(test_set[5252:5268],model)

Prediction: tf.Tensor([[7.30168754]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[9.31324764]], shape=(1, 1), dtype=float64) True Value: [7.7]
Prediction: tf.Tensor([[1.46651534]], shape=(1, 1), dtype=float64) True Value: [2.75]
Prediction: tf.Tensor([[6.71412686]], shape=(1, 1), dtype=float64) True Value: [11.]
Prediction: tf.Tensor([[6.28705386]], shape=(1, 1), dtype=float64) True Value: [8.]
Prediction: tf.Tensor([[2.90737914]], shape=(1, 1), dtype=float64) True Value: [5.]
Prediction: tf.Tensor([[1.67811673]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[6.86101938]], shape=(1, 1), dtype=float64) True Value: [7.49]
Prediction: tf.Tensor([[8.27003801]], shape=(1, 1), dtype=float64) True Value: [7.]
Prediction: tf.Tensor([[8.23865459]], shape=(1, 1), dtype=float64) True Value: [8.1]
Prediction: tf.Tensor([[5.10661524]], shape=(1, 1), dtype=float64) True Value: [5.]
Prediction: tf.Tensor([[5.51156613]], shape=(1, 1), dtype=float64) Tr

In [ ]:
#increased learning rate
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(1)
])

for i in range(10):
    print("EPOCH: "+str(i))
    train_epoch(model)

EPOCH: 0
LOSS: tf.Tensor(2.285295009613037, shape=(), dtype=float64)
LOSS: tf.Tensor(2.668794870376587, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 1
LOSS: tf.Tensor(1.7755510807037354, shape=(), dtype=float64)
LOSS: tf.Tensor(1.835989236831665, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 2
LOSS: tf.Tensor(1.5865137577056885, shape=(), dtype=float64)
LOSS: tf.Tensor(1.8164700269699097, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 3
LOSS: tf.Tensor(1.580286979675293, shape=(), dtype=float64)
LOSS: tf.Tensor(1.8095293045043945, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 4
LOSS: tf.Tensor(1.5769845247268677, shape=(), dtype=float64)
LOSS: tf.Tensor(1.805495023727417, shape=(), dtype=float64)
NAN Count: 359 Successly trained batches: 1708
EPOCH: 5
LOSS: tf.Tensor(1.5749056339263916, shape=(), dtype=float64)
LOSS: tf.Tensor(1.8029589653015137, shape=(),